FROM python:3.9

Install cookiecutter
RUN pip install cookiecutter

Set working directory
WORKDIR /app

Copy required files
COPY cookiecutter.json .
COPY templates/ templates/

Create a script for downloading the folder structure
RUN echo '#!/bin/bash' >> /app/download.sh
&& echo 'mkdir -p /app/output' >> /app/download.sh
&& echo 'cd /app/output' >> /app/download.sh
&& echo 'wget --recursive --no-parent --no-host-directories http://localhost:8000/output/' >> /app/download.sh
&& chmod +x /app/download.sh

Run cookiecutter command and save artifacts
CMD cookiecutter --no-input templates/my-template
&& cp -R my-template/* /app/output/
&& /app/download.sh